/**
 * ADIF (Amateur Data Interchange Format) parser + writer.
 *
 * ADIF is THE universal interchange for ham radio QSO logs (every
 * logging app, N1MM, Log4OM, HRD, ACLog, fldigi, WSJT-X, exports
 * and imports it). Format is tag-length-value:
 *
 *   <TAG:length>value
 *
 * For example:
 *   <CALL:5>K1ABC<QSO_DATE:8>20240101<TIME_ON:4>1200<BAND:3>20m
 *   <MODE:3>SSB<RST_SENT:2>59<RST_RCVD:2>59<EOR>
 *
 * Records end with `<EOR>`. The header (everything before `<EOH>`) holds
 * metadata like the source program; we preserve `ADIF_VER`, `PROGRAMID`,
 * and `PROGRAMVERSION` for round-trip but skip the rest.
 */

export interface AdifQso {
  /** Raw fields keyed by uppercase ADIF tag name. */
  fields: Record<string, string>;
}

export interface ParsedAdif {
  header: Record<string, string>;
  qsos: AdifQso[];
}

/**
 * Walk the file and pull `<TAG:length>value` triples. We respect the
 * declared length (which can be longer than apparent because some QSO
 * fields contain `<` characters, e.g. comments).
 */
export function parseAdif(text: string): ParsedAdif {
  const header: Record<string, string> = {};
  const qsos: AdifQso[] = [];
  let i = 0;
  let inHeader = true;
  let current: Record<string, string> = {};
  let currentEmpty = true;

  while (i < text.length) {
    const lt = text.indexOf("<", i);
    if (lt < 0) break;
    const gt = text.indexOf(">", lt);
    if (gt < 0) break;
    const tagSpec = text.slice(lt + 1, gt);
    const colon = tagSpec.indexOf(":");
    const tagName = (colon >= 0 ? tagSpec.slice(0, colon) : tagSpec).toUpperCase();

    if (tagName === "EOH") {
      inHeader = false;
      i = gt + 1;
      continue;
    }
    if (tagName === "EOR") {
      if (!currentEmpty) qsos.push({ fields: current });
      current = {};
      currentEmpty = true;
      i = gt + 1;
      continue;
    }

    let length = 0;
    if (colon >= 0) {
      // Tag may include data type indicator: "<NAME:5:S>", split on : and take first numeric.
      const parts = tagSpec.slice(colon + 1).split(":");
      length = parseInt(parts[0], 10);
      if (isNaN(length)) length = 0;
    }
    const value = text.slice(gt + 1, gt + 1 + length);
    if (inHeader) {
      header[tagName] = value;
    } else {
      current[tagName] = value;
      currentEmpty = false;
    }
    i = gt + 1 + length;
  }

  // Some files lack a final <EOR>; flush any partial record.
  if (!currentEmpty) qsos.push({ fields: current });

  return { header, qsos };
}

export function buildAdif(parsed: ParsedAdif): string {
  const out: string[] = [];
  out.push("Generated by client-conversion\n");
  const header = {
    ADIF_VER: "3.1.4",
    PROGRAMID: "client-conversion",
    ...parsed.header,
  };
  for (const [k, v] of Object.entries(header)) {
    if (v == null) continue;
    const s = String(v);
    out.push(`<${k}:${s.length}>${s}`);
  }
  out.push(`<EOH>\n`);
  for (const qso of parsed.qsos) {
    for (const [k, v] of Object.entries(qso.fields)) {
      // Skip absent fields: a converter may build a record with optional
      // fields undefined (e.g. a Cabrillo QSO line missing the received
      // exchange), and `undefined.length` would otherwise crash the run.
      if (v == null) continue;
      const s = String(v);
      out.push(`<${k}:${s.length}>${s}`);
    }
    out.push(`<EOR>\n`);
  }
  return out.join("");
}
