/**
 * OBJ writer. Wavefront OBJ is plain text:
 *   v x y z       (one vertex per line)
 *   f a b c       (one triangle per line, 1-indexed vertex references)
 *
 * No materials, normals, or texture coordinates, just geometry. That
 * matches what our 3MF/STL parsers extract anyway (we don't preserve
 * normals/UVs through the unified Mesh shape).
 */

import type { Mesh } from "./mesh";

export function buildObj(mesh: Mesh): string {
  const lines: string[] = ["# Generated by client-conversion"];
  const vCount = mesh.vertices.length / 3;
  for (let i = 0; i < vCount; i++) {
    lines.push(`v ${mesh.vertices[i * 3]} ${mesh.vertices[i * 3 + 1]} ${mesh.vertices[i * 3 + 2]}`);
  }
  const tCount = mesh.triangles.length / 3;
  for (let i = 0; i < tCount; i++) {
    // OBJ is 1-indexed
    lines.push(`f ${mesh.triangles[i * 3] + 1} ${mesh.triangles[i * 3 + 1] + 1} ${mesh.triangles[i * 3 + 2] + 1}`);
  }
  return lines.join("\n") + "\n";
}
