/**
 * Technical docs (AsciiDoc), diagrams (DOT/Graphviz), and HTTP-archive
 * (HAR <-> curl) batch tests.
 *
 * Non-shallow: structural assertions on the actual rendered output
 * (Asciidoctor's HTML class signatures, Graphviz SVG width/viewBox,
 * curl POSIX quoting). HAR <-> curl roundtrip preserved by URL +
 * method + header + body parity, not just shape.
 */

import { describe, it, expect } from "vitest";
import { run } from "../src/lib/engine/runner";
import { getMeta } from "../src/lib/engine/registry-meta";
import { fileFromText } from "./fixtures/text-fixtures";

describe("dot-to-svg", () => {
  it("renders a real Graphviz SVG with width and viewBox", async () => {
    const dot = "digraph G { rankdir=LR; a -> b -> c; b -> d; }";
    const result = await run(
      "dot-to-svg",
      fileFromText("g.dot", dot, "text/vnd.graphviz"),
    );
    const svg = await result.blob.text();
    expect(result.blob.type).toContain("svg+xml");
    expect(svg).toMatch(/<svg[^>]+width="\d+(?:\.\d+)?(?:pt)?"/);
    expect(svg).toMatch(/viewBox="[^"]+"/);
    // Graphviz embeds the original graph type and a generator comment.
    expect(svg).toMatch(/Generated by graphviz/i);
    expect(svg.length).toBeGreaterThan(500);
  }, 30000);

  it("rejects malformed DOT", async () => {
    await expect(
      run("dot-to-svg", fileFromText("bad.dot", "this is not dot {{", "text/vnd.graphviz")),
    ).rejects.toThrow(/syntax|render/i);
  }, 30000);
});

describe("har-to-curl", () => {
  it("emits one POSIX-quoted curl per HAR entry", async () => {
    const har = JSON.stringify({
      log: {
        version: "1.2",
        entries: [
          {
            request: {
              method: "GET",
              url: "https://api.example.com/users/1",
              headers: [
                { name: "Accept", value: "application/json" },
                { name: ":method", value: "GET" }, // pseudo-header, should be filtered
              ],
            },
          },
          {
            request: {
              method: "POST",
              url: "https://api.example.com/x",
              headers: [{ name: "Content-Type", value: "application/json" }],
              postData: { mimeType: "application/json", text: `{"name":"Alice's machine"}` },
            },
          },
        ],
      },
    });
    const result = await run(
      "har-to-curl",
      fileFromText("net.har", har, "application/har+json"),
    );
    const text = await result.blob.text();
    expect(result.blob.type).toContain("application/x-sh");
    // GET command quotes URL and doesn't emit -X GET (curl default).
    expect(text).toMatch(/^curl 'https:\/\/api\.example\.com\/users\/1'/m);
    expect(text).not.toMatch(/-X GET/);
    // POST emits -X POST + -H + --data-raw with the body escaped.
    expect(text).toMatch(/curl -X POST 'https:\/\/api\.example\.com\/x'/);
    expect(text).toContain("-H 'Content-Type: application/json'");
    // Single-quote escape via POSIX '\'' replacement for "Alice's".
    expect(text).toMatch(/Alice'\\''s machine/);
    // Pseudo-header filtered out.
    expect(text).not.toContain(":method");
  });

  it("rejects HAR missing log.entries", async () => {
    await expect(
      run(
        "har-to-curl",
        fileFromText("bad.har", JSON.stringify({ log: {} }), "application/har+json"),
      ),
    ).rejects.toThrow(/log\.entries/);
  });
});

describe("curl-to-har", () => {
  it("parses GET and POST curl into HAR entries", async () => {
    const script = `curl https://api.example.com/users
curl -X POST 'https://api.example.com/x' -H 'Content-Type: application/json' -d '{"a":1}'
`;
    const result = await run(
      "curl-to-har",
      fileFromText("s.sh", script, "text/plain"),
    );
    expect(result.blob.type).toContain("har+json");
    const har = JSON.parse(await result.blob.text());
    expect(har.log.version).toBe("1.2");
    expect(har.log.entries).toHaveLength(2);

    const e1 = har.log.entries[0];
    expect(e1.request.method).toBe("GET");
    expect(e1.request.url).toBe("https://api.example.com/users");

    const e2 = har.log.entries[1];
    expect(e2.request.method).toBe("POST");
    expect(e2.request.url).toBe("https://api.example.com/x");
    expect(
      e2.request.headers.find((h: { name: string }) => h.name === "Content-Type")?.value,
    ).toBe("application/json");
    expect(e2.request.postData.text).toBe('{"a":1}');
    expect(e2.request.postData.mimeType).toBe("application/json");
  });

  it("supports line continuations via backslash", async () => {
    const script = `curl https://api.example.com/x \\
  -H 'Accept: application/json' \\
  -H 'X-Demo: yes'
`;
    const result = await run(
      "curl-to-har",
      fileFromText("c.sh", script, "text/plain"),
    );
    const har = JSON.parse(await result.blob.text());
    expect(har.log.entries).toHaveLength(1);
    expect(har.log.entries[0].request.headers.map((h: { name: string }) => h.name)).toEqual([
      "Accept",
      "X-Demo",
    ]);
  });

  it("round-trip: HAR -> curl -> HAR preserves URL, method, headers, body", async () => {
    const original = {
      log: {
        version: "1.2",
        entries: [
          {
            request: {
              method: "POST",
              url: "https://api.example.com/orders",
              headers: [
                { name: "Accept", value: "application/json" },
                { name: "Authorization", value: "Bearer abc123" },
              ],
              postData: { mimeType: "application/json", text: '{"sku":"A1"}' },
            },
          },
        ],
      },
    };
    const r1 = await run(
      "har-to-curl",
      fileFromText("in.har", JSON.stringify(original), "application/har+json"),
    );
    const r2 = await run(
      "curl-to-har",
      new File([await r1.blob.text()], "rt.sh", { type: "text/plain" }) as unknown as File,
    );
    const back = JSON.parse(await r2.blob.text());
    expect(back.log.entries).toHaveLength(1);
    expect(back.log.entries[0].request.method).toBe("POST");
    expect(back.log.entries[0].request.url).toBe("https://api.example.com/orders");
    const headerMap = Object.fromEntries(
      back.log.entries[0].request.headers.map((h: { name: string; value: string }) => [
        h.name,
        h.value,
      ]),
    );
    expect(headerMap.Accept).toBe("application/json");
    expect(headerMap.Authorization).toBe("Bearer abc123");
    expect(back.log.entries[0].request.postData.text).toBe('{"sku":"A1"}');
  });

  it("rejects input with no curl commands", async () => {
    await expect(
      run(
        "curl-to-har",
        fileFromText("nope.sh", "echo hello\nls -la\n", "text/plain"),
      ),
    ).rejects.toThrow(/No curl commands/);
  });
});

describe("registry meta wiring", () => {
  const ids = [
    "asciidoc-to-html",
    "dot-to-svg",
    "dot-to-png",
    "har-to-curl",
    "curl-to-har",
  ] as const;

  for (const id of ids) {
    it(`${id} is registered with non-empty meta`, () => {
      const meta = getMeta(id);
      expect(meta).toBeDefined();
      expect(meta!.label).toBeTruthy();
      expect(meta!.accept.length).toBeGreaterThan(0);
      expect(meta!.toMime).toBeTruthy();
    });
  }
});
