/**
 * Static metadata catalog for every converter — generated by
 * scripts/generate-registry-meta.ts. DO NOT EDIT BY HAND.
 *
 * Used at build time by Next.js page rendering so we can render all
 * 193+ tool pages without dynamically importing the converter
 * implementations (which pull in heavy WASM/parser deps).
 *
 * The runtime loader in registry.ts is still the source of truth for
 * actually executing conversions — this file is just a build-time
 * speedup for metadata access.
 *
 * Regenerate with: `npx tsx scripts/generate-registry-meta.ts`
 */

export interface ConverterMeta {
  label: string;
  accept: string[];
  fromMime: string[];
  toMime: string;
  maxFileSizeBytes?: number;
}

export const REGISTRY_META: Record<string, ConverterMeta> = {
  "heic-to-jpg": {
    "label": "HEIC → JPG",
    "accept": [
      ".heic",
      ".heif"
    ],
    "fromMime": [
      "image/heic",
      "image/heif"
    ],
    "toMime": "image/jpeg",
    "maxFileSizeBytes": 104857600
  },
  "heic-to-png": {
    "label": "HEIC → PNG",
    "accept": [
      ".heic",
      ".heif"
    ],
    "fromMime": [
      "image/heic",
      "image/heif"
    ],
    "toMime": "image/png",
    "maxFileSizeBytes": 104857600
  },
  "heic-to-webp": {
    "label": "HEIC → WebP",
    "accept": [
      ".heic",
      ".heif"
    ],
    "fromMime": [
      "image/heic",
      "image/heif"
    ],
    "toMime": "image/webp",
    "maxFileSizeBytes": 104857600
  },
  "jpg-to-png": {
    "label": "JPG → PNG",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "image/png"
  },
  "jpg-to-webp": {
    "label": "JPG → WebP",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "image/webp"
  },
  "png-to-jpg": {
    "label": "PNG → JPG",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "image/jpeg"
  },
  "png-to-webp": {
    "label": "PNG → WebP",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "image/webp"
  },
  "webp-to-jpg": {
    "label": "WebP → JPG",
    "accept": [
      ".webp"
    ],
    "fromMime": [
      "image/webp"
    ],
    "toMime": "image/jpeg"
  },
  "webp-to-png": {
    "label": "WebP → PNG",
    "accept": [
      ".webp"
    ],
    "fromMime": [
      "image/webp"
    ],
    "toMime": "image/png"
  },
  "avif-to-jpg": {
    "label": "AVIF → JPG",
    "accept": [
      ".avif"
    ],
    "fromMime": [
      "image/avif"
    ],
    "toMime": "image/jpeg"
  },
  "avif-to-png": {
    "label": "AVIF → PNG",
    "accept": [
      ".avif"
    ],
    "fromMime": [
      "image/avif"
    ],
    "toMime": "image/png"
  },
  "avif-to-webp": {
    "label": "AVIF → WebP",
    "accept": [
      ".avif"
    ],
    "fromMime": [
      "image/avif"
    ],
    "toMime": "image/webp"
  },
  "bmp-to-jpg": {
    "label": "BMP → JPG",
    "accept": [
      ".bmp"
    ],
    "fromMime": [
      "image/bmp",
      "image/x-bmp"
    ],
    "toMime": "image/jpeg"
  },
  "bmp-to-png": {
    "label": "BMP → PNG",
    "accept": [
      ".bmp"
    ],
    "fromMime": [
      "image/bmp",
      "image/x-bmp"
    ],
    "toMime": "image/png"
  },
  "gif-to-jpg": {
    "label": "GIF → JPG",
    "accept": [
      ".gif"
    ],
    "fromMime": [
      "image/gif"
    ],
    "toMime": "image/jpeg"
  },
  "gif-to-png": {
    "label": "GIF → PNG",
    "accept": [
      ".gif"
    ],
    "fromMime": [
      "image/gif"
    ],
    "toMime": "image/png"
  },
  "svg-to-png": {
    "label": "SVG → PNG",
    "accept": [
      ".svg"
    ],
    "fromMime": [
      "image/svg+xml"
    ],
    "toMime": "image/png"
  },
  "svg-to-jpg": {
    "label": "SVG → JPG",
    "accept": [
      ".svg"
    ],
    "fromMime": [
      "image/svg+xml"
    ],
    "toMime": "image/jpeg"
  },
  "pdf-to-jpg": {
    "label": "PDF → JPG",
    "accept": [
      ".pdf"
    ],
    "fromMime": [
      "application/pdf"
    ],
    "toMime": "image/jpeg",
    "maxFileSizeBytes": 52428800
  },
  "pdf-to-png": {
    "label": "PDF → PNG",
    "accept": [
      ".pdf"
    ],
    "fromMime": [
      "application/pdf"
    ],
    "toMime": "image/png",
    "maxFileSizeBytes": 52428800
  },
  "jpg-to-pdf": {
    "label": "JPG → PDF",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 52428800
  },
  "png-to-pdf": {
    "label": "PNG → PDF",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 52428800
  },
  "heic-to-pdf": {
    "label": "HEIC → PDF",
    "accept": [
      ".heic",
      ".heif"
    ],
    "fromMime": [
      "image/heic",
      "image/heif"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 104857600
  },
  "webp-to-pdf": {
    "label": "WebP → PDF",
    "accept": [
      ".webp"
    ],
    "fromMime": [
      "image/webp"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 52428800
  },
  "compress-pdf": {
    "label": "Compress PDF",
    "accept": [
      ".pdf"
    ],
    "fromMime": [
      "application/pdf"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 104857600
  },
  "image-to-text": {
    "label": "Image → Text",
    "accept": [
      ".jpg",
      ".jpeg",
      ".png",
      ".webp",
      ".bmp",
      ".gif"
    ],
    "fromMime": [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/bmp",
      "image/gif"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 31457280
  },
  "jpg-to-text": {
    "label": "JPG → Text",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 31457280
  },
  "png-to-text": {
    "label": "PNG → Text",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 31457280
  },
  "pdf-to-text": {
    "label": "PDF → Text",
    "accept": [
      ".pdf"
    ],
    "fromMime": [
      "application/pdf"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 52428800
  },
  "jpg-to-avif": {
    "label": "JPG → AVIF",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "image/avif",
    "maxFileSizeBytes": 31457280
  },
  "png-to-avif": {
    "label": "PNG → AVIF",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "image/avif",
    "maxFileSizeBytes": 31457280
  },
  "webp-to-avif": {
    "label": "WebP → AVIF",
    "accept": [
      ".webp"
    ],
    "fromMime": [
      "image/webp"
    ],
    "toMime": "image/avif",
    "maxFileSizeBytes": 31457280
  },
  "tiff-to-jpg": {
    "label": "TIFF → JPG",
    "accept": [
      ".tiff",
      ".tif"
    ],
    "fromMime": [
      "image/tiff",
      "image/x-tiff"
    ],
    "toMime": "image/jpeg",
    "maxFileSizeBytes": 104857600
  },
  "tiff-to-png": {
    "label": "TIFF → PNG",
    "accept": [
      ".tiff",
      ".tif"
    ],
    "fromMime": [
      "image/tiff",
      "image/x-tiff"
    ],
    "toMime": "image/png",
    "maxFileSizeBytes": 104857600
  },
  "tiff-to-pdf": {
    "label": "TIFF → PDF",
    "accept": [
      ".tiff",
      ".tif"
    ],
    "fromMime": [
      "image/tiff",
      "image/x-tiff"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 104857600
  },
  "mp4-to-mp3": {
    "label": "MP4 → MP3",
    "accept": [
      ".mp4",
      ".m4v"
    ],
    "fromMime": [
      "video/mp4"
    ],
    "toMime": "audio/mpeg",
    "maxFileSizeBytes": 209715200
  },
  "mp4-to-gif": {
    "label": "MP4 → GIF",
    "accept": [
      ".mp4",
      ".m4v"
    ],
    "fromMime": [
      "video/mp4"
    ],
    "toMime": "image/gif",
    "maxFileSizeBytes": 104857600
  },
  "mov-to-mp4": {
    "label": "MOV → MP4",
    "accept": [
      ".mov",
      ".qt"
    ],
    "fromMime": [
      "video/quicktime",
      "video/mov"
    ],
    "toMime": "video/mp4",
    "maxFileSizeBytes": 524288000
  },
  "webm-to-mp4": {
    "label": "WebM → MP4",
    "accept": [
      ".webm"
    ],
    "fromMime": [
      "video/webm"
    ],
    "toMime": "video/mp4",
    "maxFileSizeBytes": 209715200
  },
  "avi-to-mp4": {
    "label": "AVI → MP4",
    "accept": [
      ".avi"
    ],
    "fromMime": [
      "video/avi",
      "video/x-msvideo"
    ],
    "toMime": "video/mp4",
    "maxFileSizeBytes": 209715200
  },
  "mkv-to-mp4": {
    "label": "MKV → MP4",
    "accept": [
      ".mkv"
    ],
    "fromMime": [
      "video/x-matroska",
      "video/mkv"
    ],
    "toMime": "video/mp4",
    "maxFileSizeBytes": 524288000
  },
  "mp3-to-wav": {
    "label": "MP3 → WAV",
    "accept": [
      ".mp3"
    ],
    "fromMime": [
      "audio/mpeg",
      "audio/mp3"
    ],
    "toMime": "audio/wav",
    "maxFileSizeBytes": 209715200
  },
  "wav-to-mp3": {
    "label": "WAV → MP3",
    "accept": [
      ".wav"
    ],
    "fromMime": [
      "audio/wav",
      "audio/x-wav"
    ],
    "toMime": "audio/mpeg",
    "maxFileSizeBytes": 209715200
  },
  "m4a-to-mp3": {
    "label": "M4A → MP3",
    "accept": [
      ".m4a"
    ],
    "fromMime": [
      "audio/mp4",
      "audio/m4a",
      "audio/x-m4a"
    ],
    "toMime": "audio/mpeg",
    "maxFileSizeBytes": 209715200
  },
  "flac-to-mp3": {
    "label": "FLAC → MP3",
    "accept": [
      ".flac"
    ],
    "fromMime": [
      "audio/flac",
      "audio/x-flac"
    ],
    "toMime": "audio/mpeg",
    "maxFileSizeBytes": 524288000
  },
  "ogg-to-mp3": {
    "label": "OGG → MP3",
    "accept": [
      ".ogg",
      ".oga"
    ],
    "fromMime": [
      "audio/ogg",
      "application/ogg"
    ],
    "toMime": "audio/mpeg",
    "maxFileSizeBytes": 209715200
  },
  "docx-to-html": {
    "label": "DOCX → HTML",
    "accept": [
      ".docx"
    ],
    "fromMime": [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 52428800
  },
  "docx-to-txt": {
    "label": "DOCX → TXT",
    "accept": [
      ".docx"
    ],
    "fromMime": [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 52428800
  },
  "docx-to-pdf": {
    "label": "DOCX → PDF",
    "accept": [
      ".docx"
    ],
    "fromMime": [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 52428800
  },
  "xlsx-to-csv": {
    "label": "XLSX → CSV",
    "accept": [
      ".xlsx",
      ".xls"
    ],
    "fromMime": [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "xlsx-to-json": {
    "label": "XLSX → JSON",
    "accept": [
      ".xlsx",
      ".xls"
    ],
    "fromMime": [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-xlsx": {
    "label": "CSV → XLSX",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-json": {
    "label": "CSV → JSON",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 52428800
  },
  "json-to-csv": {
    "label": "JSON → CSV",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "json-to-xlsx": {
    "label": "JSON → XLSX",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "maxFileSizeBytes": 52428800
  },
  "yaml-to-json": {
    "label": "YAML → JSON",
    "accept": [
      ".yaml",
      ".yml"
    ],
    "fromMime": [
      "application/x-yaml",
      "text/yaml",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 20971520
  },
  "json-to-yaml": {
    "label": "JSON → YAML",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/x-yaml",
    "maxFileSizeBytes": 20971520
  },
  "toml-to-json": {
    "label": "TOML → JSON",
    "accept": [
      ".toml"
    ],
    "fromMime": [
      "application/toml",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 10485760
  },
  "json-to-toml": {
    "label": "JSON → TOML",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/toml",
    "maxFileSizeBytes": 10485760
  },
  "srt-to-vtt": {
    "label": "SRT → WebVTT",
    "accept": [
      ".srt"
    ],
    "fromMime": [
      "text/plain",
      "application/x-subrip"
    ],
    "toMime": "text/vtt",
    "maxFileSizeBytes": 10485760
  },
  "vtt-to-srt": {
    "label": "WebVTT → SRT",
    "accept": [
      ".vtt"
    ],
    "fromMime": [
      "text/vtt",
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "csv-to-tsv": {
    "label": "CSV → TSV",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv",
      "text/plain"
    ],
    "toMime": "text/tab-separated-values",
    "maxFileSizeBytes": 52428800
  },
  "tsv-to-csv": {
    "label": "TSV → CSV",
    "accept": [
      ".tsv",
      ".tab"
    ],
    "fromMime": [
      "text/tab-separated-values",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "xml-to-json": {
    "label": "XML → JSON",
    "accept": [
      ".xml"
    ],
    "fromMime": [
      "application/xml",
      "text/xml",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 20971520
  },
  "json-to-xml": {
    "label": "JSON → XML",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/xml",
    "maxFileSizeBytes": 20971520
  },
  "markdown-to-html": {
    "label": "Markdown → HTML",
    "accept": [
      ".md",
      ".markdown"
    ],
    "fromMime": [
      "text/markdown",
      "text/x-markdown",
      "text/plain"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 10485760
  },
  "html-to-markdown": {
    "label": "HTML → Markdown",
    "accept": [
      ".html",
      ".htm",
      ".xhtml"
    ],
    "fromMime": [
      "text/html",
      "application/xhtml+xml",
      "text/plain"
    ],
    "toMime": "text/markdown",
    "maxFileSizeBytes": 10485760
  },
  "markdown-to-pdf": {
    "label": "Markdown → PDF",
    "accept": [
      ".md",
      ".markdown"
    ],
    "fromMime": [
      "text/markdown",
      "text/x-markdown",
      "text/plain"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 10485760
  },
  "epub-to-text": {
    "label": "EPUB → Text",
    "accept": [
      ".epub"
    ],
    "fromMime": [
      "application/epub+zip"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 104857600
  },
  "epub-to-html": {
    "label": "EPUB → HTML",
    "accept": [
      ".epub"
    ],
    "fromMime": [
      "application/epub+zip"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 104857600
  },
  "epub-to-pdf": {
    "label": "EPUB → PDF",
    "accept": [
      ".epub"
    ],
    "fromMime": [
      "application/epub+zip"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 104857600
  },
  "ofx-to-csv": {
    "label": "OFX → CSV",
    "accept": [
      ".ofx"
    ],
    "fromMime": [
      "application/x-ofx",
      "application/vnd.intu.qbo",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 20971520
  },
  "qfx-to-csv": {
    "label": "QFX → CSV",
    "accept": [
      ".qfx"
    ],
    "fromMime": [
      "application/vnd.intu.qfx",
      "application/x-ofx",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 20971520
  },
  "qbo-to-csv": {
    "label": "QBO → CSV",
    "accept": [
      ".qbo"
    ],
    "fromMime": [
      "application/vnd.intu.qbo",
      "application/x-ofx",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 20971520
  },
  "qif-to-csv": {
    "label": "QIF → CSV",
    "accept": [
      ".qif"
    ],
    "fromMime": [
      "application/qif",
      "application/x-qif",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-ofx": {
    "label": "CSV → OFX",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/x-ofx",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-qfx": {
    "label": "CSV → QFX",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/vnd.intu.qfx",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-qbo": {
    "label": "CSV → QBO",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/vnd.intu.qbo",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-qif": {
    "label": "CSV → QIF",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/qif",
    "maxFileSizeBytes": 20971520
  },
  "ofx-to-qif": {
    "label": "OFX → QIF",
    "accept": [
      ".ofx"
    ],
    "fromMime": [
      "application/x-ofx",
      "text/plain"
    ],
    "toMime": "application/qif",
    "maxFileSizeBytes": 20971520
  },
  "qif-to-ofx": {
    "label": "QIF → OFX",
    "accept": [
      ".qif"
    ],
    "fromMime": [
      "application/qif",
      "text/plain"
    ],
    "toMime": "application/x-ofx",
    "maxFileSizeBytes": 20971520
  },
  "apple-health-to-csv": {
    "label": "Apple Health → CSV",
    "accept": [
      ".zip",
      ".xml"
    ],
    "fromMime": [
      "application/zip",
      "text/xml",
      "application/xml"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 524288000
  },
  "apple-health-to-json": {
    "label": "Apple Health → JSON",
    "accept": [
      ".zip",
      ".xml"
    ],
    "fromMime": [
      "application/zip",
      "text/xml",
      "application/xml"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 524288000
  },
  "apple-health-heart-rate-to-csv": {
    "label": "Apple Health Heart Rate → CSV",
    "accept": [
      ".zip",
      ".xml"
    ],
    "fromMime": [
      "application/zip",
      "text/xml",
      "application/xml"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 524288000
  },
  "apple-health-steps-to-csv": {
    "label": "Apple Health Steps → CSV",
    "accept": [
      ".zip",
      ".xml"
    ],
    "fromMime": [
      "application/zip",
      "text/xml",
      "application/xml"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 524288000
  },
  "apple-health-sleep-to-csv": {
    "label": "Apple Health Sleep → CSV",
    "accept": [
      ".zip",
      ".xml"
    ],
    "fromMime": [
      "application/zip",
      "text/xml",
      "application/xml"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 524288000
  },
  "apple-health-workouts-to-csv": {
    "label": "Apple Health Workouts → CSV",
    "accept": [
      ".zip",
      ".xml"
    ],
    "fromMime": [
      "application/zip",
      "text/xml",
      "application/xml"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 524288000
  },
  "kindle-clippings-to-csv": {
    "label": "Kindle Clippings → CSV",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "kindle-clippings-to-json": {
    "label": "Kindle Clippings → JSON",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 52428800
  },
  "kindle-clippings-to-markdown": {
    "label": "Kindle Clippings → Markdown",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/markdown",
    "maxFileSizeBytes": 52428800
  },
  "kindle-clippings-to-obsidian-md": {
    "label": "Kindle Clippings → Obsidian (.md)",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/markdown",
    "maxFileSizeBytes": 52428800
  },
  "kindle-clippings-to-notion-csv": {
    "label": "Kindle Clippings → Notion (.csv)",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "kindle-clippings-to-readwise-csv": {
    "label": "Kindle Clippings → Readwise (.csv)",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "gedcom-to-csv": {
    "label": "GEDCOM → CSV",
    "accept": [
      ".ged",
      ".gedcom"
    ],
    "fromMime": [
      "text/plain",
      "application/x-gedcom"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "gedcom-to-json": {
    "label": "GEDCOM → JSON",
    "accept": [
      ".ged",
      ".gedcom"
    ],
    "fromMime": [
      "text/plain",
      "application/x-gedcom"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 52428800
  },
  "gedcom-to-html": {
    "label": "GEDCOM → HTML",
    "accept": [
      ".ged",
      ".gedcom"
    ],
    "fromMime": [
      "text/plain",
      "application/x-gedcom"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 52428800
  },
  "gedcom-to-pdf": {
    "label": "GEDCOM → PDF",
    "accept": [
      ".ged",
      ".gedcom"
    ],
    "fromMime": [
      "text/plain",
      "application/x-gedcom"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-gedcom": {
    "label": "CSV → GEDCOM",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/x-gedcom",
    "maxFileSizeBytes": 52428800
  },
  "bibtex-to-ris": {
    "label": "BibTeX → RIS",
    "accept": [
      ".bib",
      ".bibtex"
    ],
    "fromMime": [
      "application/x-bibtex",
      "text/x-bibtex",
      "text/plain"
    ],
    "toMime": "application/x-research-info-systems",
    "maxFileSizeBytes": 10485760
  },
  "ris-to-bibtex": {
    "label": "RIS → BibTeX",
    "accept": [
      ".ris"
    ],
    "fromMime": [
      "application/x-research-info-systems",
      "text/plain"
    ],
    "toMime": "application/x-bibtex",
    "maxFileSizeBytes": 10485760
  },
  "nbib-to-bibtex": {
    "label": "NBIB → BibTeX",
    "accept": [
      ".nbib"
    ],
    "fromMime": [
      "application/x-research-info-systems",
      "text/plain"
    ],
    "toMime": "application/x-bibtex",
    "maxFileSizeBytes": 10485760
  },
  "nbib-to-ris": {
    "label": "NBIB → RIS",
    "accept": [
      ".nbib"
    ],
    "fromMime": [
      "application/x-research-info-systems",
      "text/plain"
    ],
    "toMime": "application/x-research-info-systems",
    "maxFileSizeBytes": 10485760
  },
  "endnote-xml-to-bibtex": {
    "label": "EndNote XML → BibTeX",
    "accept": [
      ".xml"
    ],
    "fromMime": [
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/x-bibtex",
    "maxFileSizeBytes": 20971520
  },
  "endnote-xml-to-ris": {
    "label": "EndNote XML → RIS",
    "accept": [
      ".xml"
    ],
    "fromMime": [
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/x-research-info-systems",
    "maxFileSizeBytes": 20971520
  },
  "bibtex-to-csv": {
    "label": "BibTeX → CSV",
    "accept": [
      ".bib",
      ".bibtex"
    ],
    "fromMime": [
      "application/x-bibtex",
      "text/x-bibtex",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 10485760
  },
  "ris-to-csv": {
    "label": "RIS → CSV",
    "accept": [
      ".ris"
    ],
    "fromMime": [
      "application/x-research-info-systems",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 10485760
  },
  "adif-to-csv": {
    "label": "ADIF → CSV",
    "accept": [
      ".adi",
      ".adif"
    ],
    "fromMime": [
      "text/plain",
      "application/x-adif"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-adif": {
    "label": "CSV → ADIF",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/x-adif",
    "maxFileSizeBytes": 52428800
  },
  "adif-to-cabrillo": {
    "label": "ADIF → Cabrillo",
    "accept": [
      ".adi",
      ".adif"
    ],
    "fromMime": [
      "text/plain",
      "application/x-adif"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 52428800
  },
  "adif-to-kml": {
    "label": "ADIF → KML (map)",
    "accept": [
      ".adi",
      ".adif"
    ],
    "fromMime": [
      "text/plain",
      "application/x-adif"
    ],
    "toMime": "application/vnd.google-earth.kml+xml",
    "maxFileSizeBytes": 52428800
  },
  "pgn-to-csv": {
    "label": "PGN → CSV",
    "accept": [
      ".pgn"
    ],
    "fromMime": [
      "application/x-chess-pgn",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 104857600
  },
  "pgn-to-fen": {
    "label": "PGN → FEN",
    "accept": [
      ".pgn"
    ],
    "fromMime": [
      "application/x-chess-pgn",
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 104857600
  },
  "pgn-to-json": {
    "label": "PGN → JSON",
    "accept": [
      ".pgn"
    ],
    "fromMime": [
      "application/x-chess-pgn",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 104857600
  },
  "whatsapp-chat-to-csv": {
    "label": "WhatsApp Chat → CSV",
    "accept": [
      ".txt",
      ".zip"
    ],
    "fromMime": [
      "text/plain",
      "application/zip"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 209715200
  },
  "whatsapp-chat-to-json": {
    "label": "WhatsApp Chat → JSON",
    "accept": [
      ".txt",
      ".zip"
    ],
    "fromMime": [
      "text/plain",
      "application/zip"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 209715200
  },
  "whatsapp-chat-to-html": {
    "label": "WhatsApp Chat → HTML",
    "accept": [
      ".txt",
      ".zip"
    ],
    "fromMime": [
      "text/plain",
      "application/zip"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 209715200
  },
  "whatsapp-chat-to-pdf": {
    "label": "WhatsApp Chat → PDF",
    "accept": [
      ".txt",
      ".zip"
    ],
    "fromMime": [
      "text/plain",
      "application/zip"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 209715200
  },
  "eml-to-pdf": {
    "label": "EML → PDF",
    "accept": [
      ".eml"
    ],
    "fromMime": [
      "message/rfc822",
      "text/plain"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 52428800
  },
  "eml-to-html": {
    "label": "EML → HTML",
    "accept": [
      ".eml"
    ],
    "fromMime": [
      "message/rfc822",
      "text/plain"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 52428800
  },
  "eml-to-csv": {
    "label": "EML → CSV",
    "accept": [
      ".eml"
    ],
    "fromMime": [
      "message/rfc822",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "mbox-to-eml": {
    "label": "MBOX → EML (first message)",
    "accept": [
      ".mbox"
    ],
    "fromMime": [
      "application/mbox",
      "text/plain"
    ],
    "toMime": "message/rfc822",
    "maxFileSizeBytes": 209715200
  },
  "mbox-to-pdf": {
    "label": "MBOX → PDF",
    "accept": [
      ".mbox"
    ],
    "fromMime": [
      "application/mbox",
      "text/plain"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 209715200
  },
  "pages-to-pdf": {
    "label": "Apple Pages → PDF",
    "accept": [
      ".pages"
    ],
    "fromMime": [
      "application/vnd.apple.pages",
      "application/zip"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 209715200
  },
  "numbers-to-pdf": {
    "label": "Apple Numbers → PDF",
    "accept": [
      ".numbers"
    ],
    "fromMime": [
      "application/vnd.apple.numbers",
      "application/zip"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 209715200
  },
  "keynote-to-pdf": {
    "label": "Apple Keynote → PDF",
    "accept": [
      ".key",
      ".keynote"
    ],
    "fromMime": [
      "application/vnd.apple.keynote",
      "application/zip"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 209715200
  },
  "pdf-to-docx": {
    "label": "PDF → DOCX",
    "accept": [
      ".pdf"
    ],
    "fromMime": [
      "application/pdf"
    ],
    "toMime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "maxFileSizeBytes": 52428800
  },
  "png-to-ico": {
    "label": "PNG → ICO (favicon)",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "image/x-icon",
    "maxFileSizeBytes": 10485760
  },
  "jpg-to-ico": {
    "label": "JPG → ICO (favicon)",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "image/x-icon",
    "maxFileSizeBytes": 10485760
  },
  "ico-to-png": {
    "label": "ICO → PNG",
    "accept": [
      ".ico"
    ],
    "fromMime": [
      "image/x-icon",
      "image/vnd.microsoft.icon"
    ],
    "toMime": "image/png",
    "maxFileSizeBytes": 10485760
  },
  "remove-background": {
    "label": "Remove Background",
    "accept": [
      ".png",
      ".jpg",
      ".jpeg",
      ".webp"
    ],
    "fromMime": [
      "image/png",
      "image/jpeg",
      "image/webp"
    ],
    "toMime": "image/png",
    "maxFileSizeBytes": 31457280
  },
  "twitter-archive-to-csv": {
    "label": "Twitter Archive → CSV",
    "accept": [
      ".zip"
    ],
    "fromMime": [
      "application/zip"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 1073741824
  },
  "twitter-archive-to-html": {
    "label": "Twitter Archive → HTML",
    "accept": [
      ".zip"
    ],
    "fromMime": [
      "application/zip"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 1073741824
  },
  "instagram-data-to-csv": {
    "label": "Instagram Data → CSV",
    "accept": [
      ".zip"
    ],
    "fromMime": [
      "application/zip"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 1073741824
  },
  "instagram-data-to-html": {
    "label": "Instagram Data → HTML",
    "accept": [
      ".zip"
    ],
    "fromMime": [
      "application/zip"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 1073741824
  },
  "facebook-archive-to-html": {
    "label": "Facebook Archive → HTML",
    "accept": [
      ".zip"
    ],
    "fromMime": [
      "application/zip"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 2147483648
  },
  "cube-to-3dl": {
    "label": "CUBE → 3DL",
    "accept": [
      ".cube"
    ],
    "fromMime": [
      "text/plain",
      "application/x-cube-lut"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "3dl-to-cube": {
    "label": "3DL → CUBE",
    "accept": [
      ".3dl"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "cube-to-csp": {
    "label": "CUBE → CSP",
    "accept": [
      ".cube"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "csp-to-cube": {
    "label": "CSP → CUBE",
    "accept": [
      ".csp"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "3dl-to-csp": {
    "label": "3DL → CSP",
    "accept": [
      ".3dl"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "csp-to-3dl": {
    "label": "CSP → 3DL",
    "accept": [
      ".csp"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "ase-to-gpl": {
    "label": "ASE → GPL (GIMP Palette)",
    "accept": [
      ".ase"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "gpl-to-ase": {
    "label": "GPL → ASE (Adobe)",
    "accept": [
      ".gpl"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "application/octet-stream",
    "maxFileSizeBytes": 5242880
  },
  "ase-to-aco": {
    "label": "ASE → ACO (Photoshop)",
    "accept": [
      ".ase"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "application/octet-stream",
    "maxFileSizeBytes": 5242880
  },
  "aco-to-ase": {
    "label": "ACO → ASE",
    "accept": [
      ".aco"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "application/octet-stream",
    "maxFileSizeBytes": 5242880
  },
  "aco-to-gpl": {
    "label": "ACO → GPL",
    "accept": [
      ".aco"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "gpl-to-aco": {
    "label": "GPL → ACO",
    "accept": [
      ".gpl"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "application/octet-stream",
    "maxFileSizeBytes": 5242880
  },
  "ase-to-css": {
    "label": "ASE → CSS variables",
    "accept": [
      ".ase"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "text/css",
    "maxFileSizeBytes": 5242880
  },
  "ase-to-json": {
    "label": "ASE → JSON",
    "accept": [
      ".ase"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 5242880
  },
  "hex-to-ase": {
    "label": "HEX list → ASE",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "application/octet-stream",
    "maxFileSizeBytes": 5242880
  },
  "hex-to-gpl": {
    "label": "HEX list → GPL",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "ase-to-hex": {
    "label": "ASE → HEX list",
    "accept": [
      ".ase"
    ],
    "fromMime": [
      "application/octet-stream"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "gpl-to-hex": {
    "label": "GPL → HEX list",
    "accept": [
      ".gpl"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "css-to-ase": {
    "label": "CSS → ASE",
    "accept": [
      ".css"
    ],
    "fromMime": [
      "text/css",
      "text/plain"
    ],
    "toMime": "application/octet-stream",
    "maxFileSizeBytes": 5242880
  },
  "stl-to-3mf": {
    "label": "STL → 3MF",
    "accept": [
      ".stl"
    ],
    "fromMime": [
      "model/stl",
      "application/sla"
    ],
    "toMime": "model/3mf",
    "maxFileSizeBytes": 209715200
  },
  "3mf-to-stl": {
    "label": "3MF → STL",
    "accept": [
      ".3mf"
    ],
    "fromMime": [
      "model/3mf",
      "application/zip"
    ],
    "toMime": "model/stl",
    "maxFileSizeBytes": 209715200
  },
  "obj-to-3mf": {
    "label": "OBJ → 3MF",
    "accept": [
      ".obj"
    ],
    "fromMime": [
      "model/obj",
      "text/plain"
    ],
    "toMime": "model/3mf",
    "maxFileSizeBytes": 209715200
  },
  "midi-to-musicxml": {
    "label": "MIDI → MusicXML",
    "accept": [
      ".mid",
      ".midi"
    ],
    "fromMime": [
      "audio/midi",
      "audio/x-midi"
    ],
    "toMime": "application/vnd.recordare.musicxml+xml",
    "maxFileSizeBytes": 20971520
  },
  "musicxml-to-midi": {
    "label": "MusicXML → MIDI",
    "accept": [
      ".musicxml",
      ".xml"
    ],
    "fromMime": [
      "application/vnd.recordare.musicxml+xml",
      "application/xml",
      "text/xml"
    ],
    "toMime": "audio/midi",
    "maxFileSizeBytes": 20971520
  },
  "mxl-to-musicxml": {
    "label": "MXL → MusicXML",
    "accept": [
      ".mxl"
    ],
    "fromMime": [
      "application/vnd.recordare.musicxml",
      "application/zip"
    ],
    "toMime": "application/vnd.recordare.musicxml+xml",
    "maxFileSizeBytes": 52428800
  },
  "sarif-to-csv": {
    "label": "SARIF → CSV",
    "accept": [
      ".sarif",
      ".json"
    ],
    "fromMime": [
      "application/sarif+json",
      "application/json"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 104857600
  },
  "sarif-to-html": {
    "label": "SARIF → HTML report",
    "accept": [
      ".sarif",
      ".json"
    ],
    "fromMime": [
      "application/sarif+json",
      "application/json"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 104857600
  },
  "edi-to-csv": {
    "label": "EDI X12 → CSV",
    "accept": [
      ".edi",
      ".x12",
      ".850",
      ".810",
      ".856",
      ".997"
    ],
    "fromMime": [
      "application/edi-x12",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "edifact-to-csv": {
    "label": "EDIFACT → CSV",
    "accept": [
      ".edi",
      ".edifact",
      ".txt"
    ],
    "fromMime": [
      "application/edifact",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "pacer-docket-to-csv": {
    "label": "PACER docket → CSV",
    "accept": [
      ".html",
      ".htm",
      ".zip"
    ],
    "fromMime": [
      "text/html",
      "application/zip"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 104857600
  },
  "ifc-to-csv": {
    "label": "IFC → CSV (quantity takeoff)",
    "accept": [
      ".ifc"
    ],
    "fromMime": [
      "application/x-step",
      "application/ifc",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 524288000
  },
  "ifc-to-gltf": {
    "label": "IFC → glTF (.glb)",
    "accept": [
      ".ifc"
    ],
    "fromMime": [
      "application/x-step",
      "application/ifc",
      "text/plain"
    ],
    "toMime": "model/gltf-binary",
    "maxFileSizeBytes": 524288000
  },
  "discord-chat-to-md": {
    "label": "Discord Chat → Markdown",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json"
    ],
    "toMime": "text/markdown",
    "maxFileSizeBytes": 209715200
  },
  "discord-chat-to-pdf": {
    "label": "Discord Chat → PDF",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json"
    ],
    "toMime": "application/pdf",
    "maxFileSizeBytes": 209715200
  },
  "discord-chat-summary-csv": {
    "label": "Discord Chat → Summary CSV (per author)",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 209715200
  },
  "dst-to-pes": {
    "label": "DST → PES (Brother)",
    "accept": [
      ".dst"
    ],
    "fromMime": [
      "application/x-tajima-dst",
      "application/octet-stream"
    ],
    "toMime": "application/x-pes",
    "maxFileSizeBytes": 52428800
  },
  "pes-to-dst": {
    "label": "PES → DST (Tajima)",
    "accept": [
      ".pes"
    ],
    "fromMime": [
      "application/x-pes",
      "application/octet-stream"
    ],
    "toMime": "application/x-tajima-dst",
    "maxFileSizeBytes": 52428800
  },
  "dst-to-jef": {
    "label": "DST → JEF (Janome)",
    "accept": [
      ".dst"
    ],
    "fromMime": [
      "application/x-tajima-dst",
      "application/octet-stream"
    ],
    "toMime": "application/x-jef",
    "maxFileSizeBytes": 52428800
  },
  "jef-to-dst": {
    "label": "JEF → DST",
    "accept": [
      ".jef"
    ],
    "fromMime": [
      "application/x-jef",
      "application/octet-stream"
    ],
    "toMime": "application/x-tajima-dst",
    "maxFileSizeBytes": 52428800
  },
  "pes-to-jef": {
    "label": "PES → JEF",
    "accept": [
      ".pes"
    ],
    "fromMime": [
      "application/x-pes",
      "application/octet-stream"
    ],
    "toMime": "application/x-jef",
    "maxFileSizeBytes": 52428800
  },
  "jef-to-pes": {
    "label": "JEF → PES",
    "accept": [
      ".jef"
    ],
    "fromMime": [
      "application/x-jef",
      "application/octet-stream"
    ],
    "toMime": "application/x-pes",
    "maxFileSizeBytes": 52428800
  },
  "dst-to-exp": {
    "label": "DST → EXP (Melco)",
    "accept": [
      ".dst"
    ],
    "fromMime": [
      "application/x-tajima-dst",
      "application/octet-stream"
    ],
    "toMime": "application/x-exp",
    "maxFileSizeBytes": 52428800
  },
  "exp-to-dst": {
    "label": "EXP → DST",
    "accept": [
      ".exp"
    ],
    "fromMime": [
      "application/x-exp",
      "application/octet-stream"
    ],
    "toMime": "application/x-tajima-dst",
    "maxFileSizeBytes": 52428800
  },
  "pes-to-exp": {
    "label": "PES → EXP",
    "accept": [
      ".pes"
    ],
    "fromMime": [
      "application/x-pes",
      "application/octet-stream"
    ],
    "toMime": "application/x-exp",
    "maxFileSizeBytes": 52428800
  },
  "exp-to-pes": {
    "label": "EXP → PES",
    "accept": [
      ".exp"
    ],
    "fromMime": [
      "application/x-exp",
      "application/octet-stream"
    ],
    "toMime": "application/x-pes",
    "maxFileSizeBytes": 52428800
  },
  "jef-to-exp": {
    "label": "JEF → EXP",
    "accept": [
      ".jef"
    ],
    "fromMime": [
      "application/x-jef",
      "application/octet-stream"
    ],
    "toMime": "application/x-exp",
    "maxFileSizeBytes": 52428800
  },
  "exp-to-jef": {
    "label": "EXP → JEF",
    "accept": [
      ".exp"
    ],
    "fromMime": [
      "application/x-exp",
      "application/octet-stream"
    ],
    "toMime": "application/x-jef",
    "maxFileSizeBytes": 52428800
  },
  "jpg-to-bmp": {
    "label": "JPG → BMP",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "image/bmp"
  },
  "png-to-bmp": {
    "label": "PNG → BMP",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "image/bmp"
  },
  "jpg-to-gif": {
    "label": "JPG → GIF",
    "accept": [
      ".jpg",
      ".jpeg"
    ],
    "fromMime": [
      "image/jpeg"
    ],
    "toMime": "image/gif"
  },
  "png-to-gif": {
    "label": "PNG → GIF",
    "accept": [
      ".png"
    ],
    "fromMime": [
      "image/png"
    ],
    "toMime": "image/gif"
  },
  "ico-to-jpg": {
    "label": "ICO → JPG",
    "accept": [
      ".ico"
    ],
    "fromMime": [
      "image/x-icon",
      "image/vnd.microsoft.icon"
    ],
    "toMime": "image/jpeg"
  },
  "mp3-to-m4a": {
    "label": "MP3 → M4A",
    "accept": [
      ".mp3"
    ],
    "fromMime": [
      "audio/mpeg",
      "audio/mp3"
    ],
    "toMime": "audio/mp4",
    "maxFileSizeBytes": 209715200
  },
  "mp3-to-flac": {
    "label": "MP3 → FLAC",
    "accept": [
      ".mp3"
    ],
    "fromMime": [
      "audio/mpeg",
      "audio/mp3"
    ],
    "toMime": "audio/flac",
    "maxFileSizeBytes": 209715200
  },
  "mp3-to-ogg": {
    "label": "MP3 → OGG",
    "accept": [
      ".mp3"
    ],
    "fromMime": [
      "audio/mpeg",
      "audio/mp3"
    ],
    "toMime": "audio/ogg",
    "maxFileSizeBytes": 209715200
  },
  "mp4-to-avi": {
    "label": "MP4 → AVI",
    "accept": [
      ".mp4",
      ".m4v"
    ],
    "fromMime": [
      "video/mp4"
    ],
    "toMime": "video/x-msvideo",
    "maxFileSizeBytes": 524288000
  },
  "mp4-to-mkv": {
    "label": "MP4 → MKV",
    "accept": [
      ".mp4",
      ".m4v"
    ],
    "fromMime": [
      "video/mp4"
    ],
    "toMime": "video/x-matroska",
    "maxFileSizeBytes": 524288000
  },
  "mp4-to-mov": {
    "label": "MP4 → MOV",
    "accept": [
      ".mp4",
      ".m4v"
    ],
    "fromMime": [
      "video/mp4"
    ],
    "toMime": "video/quicktime",
    "maxFileSizeBytes": 524288000
  },
  "gif-to-mp4": {
    "label": "GIF → MP4",
    "accept": [
      ".gif"
    ],
    "fromMime": [
      "image/gif"
    ],
    "toMime": "video/mp4",
    "maxFileSizeBytes": 104857600
  },
  "musicxml-to-mxl": {
    "label": "MusicXML → MXL",
    "accept": [
      ".musicxml",
      ".xml"
    ],
    "fromMime": [
      "application/vnd.recordare.musicxml+xml",
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/vnd.recordare.musicxml",
    "maxFileSizeBytes": 52428800
  },
  "cabrillo-to-adif": {
    "label": "Cabrillo → ADIF",
    "accept": [
      ".log",
      ".cbr",
      ".cabrillo"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "application/x-adif",
    "maxFileSizeBytes": 52428800
  },
  "3mf-to-obj": {
    "label": "3MF → OBJ",
    "accept": [
      ".3mf"
    ],
    "fromMime": [
      "model/3mf",
      "application/zip"
    ],
    "toMime": "model/obj",
    "maxFileSizeBytes": 209715200
  },
  "stl-to-obj": {
    "label": "STL → OBJ",
    "accept": [
      ".stl"
    ],
    "fromMime": [
      "model/stl",
      "application/sla"
    ],
    "toMime": "model/obj",
    "maxFileSizeBytes": 209715200
  },
  "obj-to-stl": {
    "label": "OBJ → STL",
    "accept": [
      ".obj"
    ],
    "fromMime": [
      "model/obj",
      "text/plain"
    ],
    "toMime": "model/stl",
    "maxFileSizeBytes": 209715200
  },
  "json-to-gedcom": {
    "label": "JSON → GEDCOM",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json"
    ],
    "toMime": "application/x-gedcom",
    "maxFileSizeBytes": 52428800
  },
  "eml-to-mbox": {
    "label": "EML → MBOX",
    "accept": [
      ".eml"
    ],
    "fromMime": [
      "message/rfc822",
      "text/plain"
    ],
    "toMime": "application/mbox",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-bibtex": {
    "label": "CSV → BibTeX",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/x-bibtex",
    "maxFileSizeBytes": 10485760
  },
  "csv-to-ris": {
    "label": "CSV → RIS",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv"
    ],
    "toMime": "application/x-research-info-systems",
    "maxFileSizeBytes": 10485760
  },
  "bibtex-to-nbib": {
    "label": "BibTeX → NBIB",
    "accept": [
      ".bib",
      ".bibtex"
    ],
    "fromMime": [
      "application/x-bibtex",
      "text/x-bibtex",
      "text/plain"
    ],
    "toMime": "application/x-research-info-systems",
    "maxFileSizeBytes": 10485760
  },
  "ris-to-nbib": {
    "label": "RIS → NBIB",
    "accept": [
      ".ris"
    ],
    "fromMime": [
      "application/x-research-info-systems",
      "text/plain"
    ],
    "toMime": "application/x-research-info-systems",
    "maxFileSizeBytes": 10485760
  },
  "bibtex-to-endnote-xml": {
    "label": "BibTeX → EndNote XML",
    "accept": [
      ".bib",
      ".bibtex"
    ],
    "fromMime": [
      "application/x-bibtex",
      "text/x-bibtex",
      "text/plain"
    ],
    "toMime": "application/xml",
    "maxFileSizeBytes": 10485760
  },
  "ris-to-endnote-xml": {
    "label": "RIS → EndNote XML",
    "accept": [
      ".ris"
    ],
    "fromMime": [
      "application/x-research-info-systems",
      "text/plain"
    ],
    "toMime": "application/xml",
    "maxFileSizeBytes": 10485760
  },
  "html-to-docx": {
    "label": "HTML → DOCX",
    "accept": [
      ".html",
      ".htm"
    ],
    "fromMime": [
      "text/html"
    ],
    "toMime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "maxFileSizeBytes": 52428800
  },
  "txt-to-docx": {
    "label": "TXT → DOCX",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "maxFileSizeBytes": 52428800
  },
  "hex-to-rgb": {
    "label": "HEX → RGB",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "rgb-to-hex": {
    "label": "RGB → HEX",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "hex-to-hsl": {
    "label": "HEX → HSL",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "hsl-to-hex": {
    "label": "HSL → HEX",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "rgb-to-hsl": {
    "label": "RGB → HSL",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "hsl-to-rgb": {
    "label": "HSL → RGB",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "rgb-to-cmyk": {
    "label": "RGB → CMYK",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "cmyk-to-rgb": {
    "label": "CMYK → RGB",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "hex-to-cmyk": {
    "label": "HEX → CMYK",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "cmyk-to-hex": {
    "label": "CMYK → HEX",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 2097152
  },
  "text-to-base64": {
    "label": "Text → Base64",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "base64-to-text": {
    "label": "Base64 → Text",
    "accept": [
      ".txt",
      ".b64"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 14680064
  },
  "text-to-url-encoded": {
    "label": "Text → URL-encoded",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "url-encoded-to-text": {
    "label": "URL-encoded → Text",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "text-to-hex": {
    "label": "Text → Hex",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "hex-to-text": {
    "label": "Hex → Text",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 10485760
  },
  "file-to-md5": {
    "label": "File → MD5 checksum",
    "accept": [
      "*"
    ],
    "fromMime": [
      "application/octet-stream",
      "*/*"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 209715200
  },
  "file-to-sha1": {
    "label": "File → SHA-1 checksum",
    "accept": [
      "*"
    ],
    "fromMime": [
      "application/octet-stream",
      "*/*"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 209715200
  },
  "file-to-sha256": {
    "label": "File → SHA-256 checksum",
    "accept": [
      "*"
    ],
    "fromMime": [
      "application/octet-stream",
      "*/*"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 209715200
  },
  "file-to-sha512": {
    "label": "File → SHA-512 checksum",
    "accept": [
      "*"
    ],
    "fromMime": [
      "application/octet-stream",
      "*/*"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 209715200
  },
  "kml-to-gpx": {
    "label": "KML → GPX",
    "accept": [
      ".kml"
    ],
    "fromMime": [
      "application/vnd.google-earth.kml+xml",
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/gpx+xml",
    "maxFileSizeBytes": 20971520
  },
  "gpx-to-kml": {
    "label": "GPX → KML",
    "accept": [
      ".gpx"
    ],
    "fromMime": [
      "application/gpx+xml",
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/vnd.google-earth.kml+xml",
    "maxFileSizeBytes": 20971520
  },
  "kml-to-geojson": {
    "label": "KML → GeoJSON",
    "accept": [
      ".kml"
    ],
    "fromMime": [
      "application/vnd.google-earth.kml+xml",
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/geo+json",
    "maxFileSizeBytes": 20971520
  },
  "geojson-to-kml": {
    "label": "GeoJSON → KML",
    "accept": [
      ".geojson",
      ".json"
    ],
    "fromMime": [
      "application/geo+json",
      "application/json",
      "text/plain"
    ],
    "toMime": "application/vnd.google-earth.kml+xml",
    "maxFileSizeBytes": 20971520
  },
  "gpx-to-geojson": {
    "label": "GPX → GeoJSON",
    "accept": [
      ".gpx"
    ],
    "fromMime": [
      "application/gpx+xml",
      "application/xml",
      "text/xml"
    ],
    "toMime": "application/geo+json",
    "maxFileSizeBytes": 20971520
  },
  "geojson-to-gpx": {
    "label": "GeoJSON → GPX",
    "accept": [
      ".geojson",
      ".json"
    ],
    "fromMime": [
      "application/geo+json",
      "application/json",
      "text/plain"
    ],
    "toMime": "application/gpx+xml",
    "maxFileSizeBytes": 20971520
  },
  "jsonl-to-json": {
    "label": "JSONL → JSON",
    "accept": [
      ".jsonl",
      ".ndjson"
    ],
    "fromMime": [
      "application/jsonl",
      "application/x-ndjson",
      "application/json",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 52428800
  },
  "json-to-jsonl": {
    "label": "JSON → JSONL",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/jsonl",
    "maxFileSizeBytes": 52428800
  },
  "jsonl-to-csv": {
    "label": "JSONL → CSV",
    "accept": [
      ".jsonl",
      ".ndjson"
    ],
    "fromMime": [
      "application/jsonl",
      "application/x-ndjson",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-jsonl": {
    "label": "CSV → JSONL",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv",
      "text/plain"
    ],
    "toMime": "application/jsonl",
    "maxFileSizeBytes": 52428800
  },
  "ini-to-json": {
    "label": "INI → JSON",
    "accept": [
      ".ini",
      ".cfg",
      ".conf"
    ],
    "fromMime": [
      "text/plain",
      "application/x-ini"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 10485760
  },
  "json-to-ini": {
    "label": "JSON → INI",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/x-ini",
    "maxFileSizeBytes": 10485760
  },
  "env-to-json": {
    "label": ".env → JSON",
    "accept": [
      ".env"
    ],
    "fromMime": [
      "text/plain",
      "application/x-env"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 5242880
  },
  "json-to-env": {
    "label": "JSON → .env",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "yaml-to-toml": {
    "label": "YAML → TOML",
    "accept": [
      ".yaml",
      ".yml"
    ],
    "fromMime": [
      "application/x-yaml",
      "text/yaml",
      "text/plain"
    ],
    "toMime": "application/toml",
    "maxFileSizeBytes": 10485760
  },
  "toml-to-yaml": {
    "label": "TOML → YAML",
    "accept": [
      ".toml"
    ],
    "fromMime": [
      "application/toml",
      "text/plain"
    ],
    "toMime": "application/x-yaml",
    "maxFileSizeBytes": 10485760
  },
  "json5-to-json": {
    "label": "JSON5 → JSON",
    "accept": [
      ".json5"
    ],
    "fromMime": [
      "application/json5",
      "application/json",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 10485760
  },
  "srt-to-sbv": {
    "label": "SRT → SBV",
    "accept": [
      ".srt"
    ],
    "fromMime": [
      "application/x-subrip",
      "text/plain"
    ],
    "toMime": "text/sbv",
    "maxFileSizeBytes": 10485760
  },
  "sbv-to-srt": {
    "label": "SBV → SRT",
    "accept": [
      ".sbv"
    ],
    "fromMime": [
      "text/sbv",
      "text/plain"
    ],
    "toMime": "application/x-subrip",
    "maxFileSizeBytes": 10485760
  },
  "ods-to-csv": {
    "label": "ODS → CSV",
    "accept": [
      ".ods",
      ".ots"
    ],
    "fromMime": [
      "application/vnd.oasis.opendocument.spreadsheet",
      "application/vnd.oasis.opendocument.spreadsheet-template"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "ods-to-xlsx": {
    "label": "ODS → XLSX",
    "accept": [
      ".ods",
      ".ots"
    ],
    "fromMime": [
      "application/vnd.oasis.opendocument.spreadsheet"
    ],
    "toMime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "maxFileSizeBytes": 52428800
  },
  "csv-to-ods": {
    "label": "CSV → ODS",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv",
      "text/plain"
    ],
    "toMime": "application/vnd.oasis.opendocument.spreadsheet",
    "maxFileSizeBytes": 52428800
  },
  "xlsx-to-ods": {
    "label": "XLSX → ODS",
    "accept": [
      ".xlsx",
      ".xls"
    ],
    "fromMime": [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel"
    ],
    "toMime": "application/vnd.oasis.opendocument.spreadsheet",
    "maxFileSizeBytes": 52428800
  },
  "ttf-to-woff": {
    "label": "TTF → WOFF",
    "accept": [
      ".ttf"
    ],
    "fromMime": [
      "font/ttf",
      "application/x-font-ttf",
      "application/font-sfnt"
    ],
    "toMime": "font/woff",
    "maxFileSizeBytes": 20971520
  },
  "woff-to-ttf": {
    "label": "WOFF → TTF",
    "accept": [
      ".woff"
    ],
    "fromMime": [
      "font/woff",
      "application/font-woff"
    ],
    "toMime": "font/ttf",
    "maxFileSizeBytes": 20971520
  },
  "otf-to-ttf": {
    "label": "OTF → TTF",
    "accept": [
      ".otf"
    ],
    "fromMime": [
      "font/otf",
      "application/x-font-otf",
      "application/font-sfnt"
    ],
    "toMime": "font/ttf",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-markdown-table": {
    "label": "CSV → Markdown table",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv",
      "text/plain"
    ],
    "toMime": "text/markdown",
    "maxFileSizeBytes": 20971520
  },
  "markdown-table-to-csv": {
    "label": "Markdown table → CSV",
    "accept": [
      ".md",
      ".markdown"
    ],
    "fromMime": [
      "text/markdown",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-html-table": {
    "label": "CSV → HTML table",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv",
      "text/plain"
    ],
    "toMime": "text/html",
    "maxFileSizeBytes": 20971520
  },
  "html-table-to-csv": {
    "label": "HTML table → CSV",
    "accept": [
      ".html",
      ".htm"
    ],
    "fromMime": [
      "text/html"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 20971520
  },
  "csv-to-sql": {
    "label": "CSV → SQL",
    "accept": [
      ".csv"
    ],
    "fromMime": [
      "text/csv",
      "application/csv",
      "text/plain"
    ],
    "toMime": "application/sql",
    "maxFileSizeBytes": 52428800
  },
  "sql-to-csv": {
    "label": "SQL → CSV",
    "accept": [
      ".sql"
    ],
    "fromMime": [
      "application/sql",
      "text/plain"
    ],
    "toMime": "text/csv",
    "maxFileSizeBytes": 52428800
  },
  "json-to-sql": {
    "label": "JSON → SQL",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "application/sql",
    "maxFileSizeBytes": 52428800
  },
  "properties-to-json": {
    "label": ".properties → JSON",
    "accept": [
      ".properties"
    ],
    "fromMime": [
      "text/plain",
      "text/x-java-properties"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 10485760
  },
  "json-to-properties": {
    "label": "JSON → .properties",
    "accept": [
      ".json"
    ],
    "fromMime": [
      "application/json",
      "text/plain"
    ],
    "toMime": "text/x-java-properties",
    "maxFileSizeBytes": 10485760
  },
  "hcl-to-json": {
    "label": "HCL → JSON",
    "accept": [
      ".hcl",
      ".tf",
      ".tfvars"
    ],
    "fromMime": [
      "text/x-hcl",
      "application/hcl",
      "text/plain"
    ],
    "toMime": "application/json",
    "maxFileSizeBytes": 10485760
  },
  "color-name-to-hex": {
    "label": "Color name → HEX",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 1048576
  },
  "hex-to-color-name": {
    "label": "HEX → Color name",
    "accept": [
      ".txt",
      ".hex"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 1048576
  },
  "unix-to-iso": {
    "label": "Unix timestamp → ISO 8601",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "iso-to-unix": {
    "label": "ISO 8601 → Unix timestamp",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  },
  "timestamp-to-readable": {
    "label": "Timestamp → Readable date",
    "accept": [
      ".txt"
    ],
    "fromMime": [
      "text/plain"
    ],
    "toMime": "text/plain",
    "maxFileSizeBytes": 5242880
  }
};

export function listToolIds(): string[] {
  return Object.keys(REGISTRY_META);
}

export function getMeta(id: string): ConverterMeta | undefined {
  return REGISTRY_META[id];
}

export function isKnownTool(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(REGISTRY_META, id);
}
