/**
 * One-shot script: load every converter in the registry once, extract
 * its static metadata (id, label, accept, fromMime, toMime,
 * maxFileSizeBytes), and write a TypeScript module containing the
 * full table as a plain object literal.
 *
 * Why: at build time, Next.js's `generateStaticParams` + per-page
 * `generateMetadata` would otherwise dynamically import all 193
 * converter modules — which transitively pulls in WASM init code,
 * heavy parsers, and other things we don't want evaluated server-
 * side. Reading static metadata from a generated file is 10-50x
 * faster.
 *
 * Run via: `npx tsx scripts/generate-registry-meta.ts`
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, "..");

async function main() {
  // Dynamic-import the registry so we can introspect every converter.
  // The registry's lazy loaders execute the actual import at this point.
  const { registry, listConverterIds } = await import(
    join(projectRoot, "src/lib/engine/registry.ts")
  );

  const ids = listConverterIds();
  const meta: Record<string, {
    label: string;
    accept: string[];
    fromMime: string[];
    toMime: string;
    maxFileSizeBytes?: number;
  }> = {};

  for (const id of ids) {
    const converter = await registry[id]();
    meta[id] = {
      label: converter.label,
      accept: converter.accept,
      fromMime: converter.fromMime,
      toMime: converter.toMime,
      maxFileSizeBytes: converter.maxFileSizeBytes,
    };
  }

  const outputPath = join(projectRoot, "src/lib/engine/registry-meta.ts");
  const content = `/**
 * Static metadata catalog for every converter — generated by
 * scripts/generate-registry-meta.ts. DO NOT EDIT BY HAND.
 *
 * Used at build time by Next.js page rendering so we can render all
 * 193+ tool pages without dynamically importing the converter
 * implementations (which pull in heavy WASM/parser deps).
 *
 * The runtime loader in registry.ts is still the source of truth for
 * actually executing conversions — this file is just a build-time
 * speedup for metadata access.
 *
 * Regenerate with: \`npx tsx scripts/generate-registry-meta.ts\`
 */

export interface ConverterMeta {
  label: string;
  accept: string[];
  fromMime: string[];
  toMime: string;
  maxFileSizeBytes?: number;
}

export const REGISTRY_META: Record<string, ConverterMeta> = ${JSON.stringify(meta, null, 2)};

export function listToolIds(): string[] {
  return Object.keys(REGISTRY_META);
}

export function getMeta(id: string): ConverterMeta | undefined {
  return REGISTRY_META[id];
}

export function isKnownTool(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(REGISTRY_META, id);
}
`;

  writeFileSync(outputPath, content, "utf-8");
  console.log(`✓ Wrote ${ids.length} converter metadata entries to ${outputPath}`);
}

main().catch((err) => {
  console.error("Failed to generate registry meta:", err);
  process.exit(1);
});
