/**
 * 3D mesh fixtures for the game-dev/DCC format batch (FBX, DAE, 3DS, PLY,
 * glTF JSON, USDZ). Every fixture encodes the SAME ground-truth solid: a cube
 * of edge length 2 centered on the origin (vertices at ±1), 8 vertices, 12
 * triangles, all faces wound outward (CCW seen from outside).
 *
 * That shape gives tests a strong invariant: the signed volume computed from
 * the triangle soup must equal exactly 8.0. A wrong vertex, a misread index,
 * a transposed axis, or a dropped face all change the volume, so asserting
 * volume + triangle count verifies the whole parse/convert/build pipeline,
 * not just "it didn't throw".
 *
 * All fixtures are hand-written against the respective format specs (not
 * generated by our own writers), so tests are independent of the code under
 * test.
 */

// 8 corners of the ±1 cube.
export const CUBE_VERTICES: ReadonlyArray<readonly [number, number, number]> = [
  [-1, -1, -1], // 0
  [1, -1, -1], // 1
  [1, 1, -1], // 2
  [-1, 1, -1], // 3
  [-1, -1, 1], // 4
  [1, -1, 1], // 5
  [1, 1, 1], // 6
  [-1, 1, 1], // 7
];

// 12 outward-wound triangles.
export const CUBE_TRIANGLES: ReadonlyArray<readonly [number, number, number]> = [
  [0, 2, 1], [0, 3, 2], // bottom (z = -1)
  [4, 5, 6], [4, 6, 7], // top (z = +1)
  [0, 1, 5], [0, 5, 4], // front (y = -1)
  [1, 2, 6], [1, 6, 5], // right (x = +1)
  [2, 3, 7], [2, 7, 6], // back (y = +1)
  [3, 0, 4], [3, 4, 7], // left (x = -1)
];

export const CUBE_TRIANGLE_COUNT = 12;
export const CUBE_VOLUME = 8;

const V = CUBE_VERTICES;
const T = CUBE_TRIANGLES;

/**
 * Signed volume of a triangle soup via the divergence theorem:
 * sum over triangles of dot(a, cross(b, c)) / 6. Exact for closed meshes;
 * outward winding gives a positive result. Used by tests to verify converted
 * geometry, robust to vertex reordering/deduplication/splitting.
 */
export function meshVolume(vertices: ArrayLike<number>, triangles: ArrayLike<number>): number {
  let vol = 0;
  for (let t = 0; t + 2 < triangles.length; t += 3) {
    const a = triangles[t] * 3;
    const b = triangles[t + 1] * 3;
    const c = triangles[t + 2] * 3;
    const ax = vertices[a], ay = vertices[a + 1], az = vertices[a + 2];
    const bx = vertices[b], by = vertices[b + 1], bz = vertices[b + 2];
    const cx = vertices[c], cy = vertices[c + 1], cz = vertices[c + 2];
    vol += ax * (by * cz - bz * cy) + ay * (bz * cx - bx * cz) + az * (bx * cy - by * cx);
  }
  return vol / 6;
}

// ---- PLY (ASCII) --------------------------------------------------------

export const CUBE_PLY_ASCII = `ply
format ascii 1.0
comment hand-written cube fixture
element vertex 8
property float x
property float y
property float z
element face 12
property list uchar int vertex_indices
end_header
${V.map((v) => v.join(" ")).join("\n")}
${T.map((t) => `3 ${t.join(" ")}`).join("\n")}
`;

/** Binary little-endian PLY of the same cube (built per spec, byte by byte). */
export function makeCubePlyBinary(): Uint8Array {
  const header =
    "ply\n" +
    "format binary_little_endian 1.0\n" +
    "element vertex 8\n" +
    "property float x\n" +
    "property float y\n" +
    "property float z\n" +
    "element face 12\n" +
    "property list uchar int vertex_indices\n" +
    "end_header\n";
  const headerBytes = new TextEncoder().encode(header);
  // 8 vertices * 12 bytes + 12 faces * (1 + 12) bytes
  const body = new ArrayBuffer(8 * 12 + 12 * 13);
  const view = new DataView(body);
  let off = 0;
  for (const v of V) {
    view.setFloat32(off, v[0], true);
    view.setFloat32(off + 4, v[1], true);
    view.setFloat32(off + 8, v[2], true);
    off += 12;
  }
  for (const t of T) {
    view.setUint8(off, 3);
    view.setInt32(off + 1, t[0], true);
    view.setInt32(off + 5, t[1], true);
    view.setInt32(off + 9, t[2], true);
    off += 13;
  }
  const out = new Uint8Array(headerBytes.length + body.byteLength);
  out.set(headerBytes, 0);
  out.set(new Uint8Array(body), headerBytes.length);
  return out;
}

// ---- glTF 2.0 (.gltf JSON with embedded data-URI buffer) -----------------

function base64FromBytes(bytes: Uint8Array): string {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  // btoa exists in happy-dom and browsers; Buffer path covers plain node.
  return typeof btoa === "function" ? btoa(bin) : Buffer.from(bytes).toString("base64");
}

/**
 * Minimal spec-conformant .gltf JSON: positions + uint16 indices in a single
 * data-URI buffer, plus a named PBR material so container-repack tests can
 * assert materials survive gltf -> glb -> gltf losslessly.
 */
export function makeCubeGltfJson(): string {
  const posBytes = 8 * 3 * 4;
  const idxBytes = 12 * 3 * 2;
  const buf = new ArrayBuffer(posBytes + idxBytes);
  const posView = new Float32Array(buf, 0, 24);
  V.forEach((v, i) => posView.set(v, i * 3));
  const idxView = new Uint16Array(buf, posBytes, 36);
  T.forEach((t, i) => idxView.set(t, i * 3));

  const gltf = {
    asset: { version: "2.0", generator: "fixture" },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, name: "Cube" }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1, material: 0, mode: 4 }] }],
    materials: [
      {
        name: "FixtureRed",
        pbrMetallicRoughness: { baseColorFactor: [1, 0, 0, 1], metallicFactor: 0.25 },
      },
    ],
    accessors: [
      { bufferView: 0, componentType: 5126, count: 8, type: "VEC3", min: [-1, -1, -1], max: [1, 1, 1] },
      { bufferView: 1, componentType: 5123, count: 36, type: "SCALAR" },
    ],
    bufferViews: [
      { buffer: 0, byteOffset: 0, byteLength: posBytes, target: 34962 },
      { buffer: 0, byteOffset: posBytes, byteLength: idxBytes, target: 34963 },
    ],
    buffers: [
      {
        byteLength: buf.byteLength,
        uri: `data:application/octet-stream;base64,${base64FromBytes(new Uint8Array(buf))}`,
      },
    ],
  };
  return JSON.stringify(gltf);
}

// ---- COLLADA (.dae) ------------------------------------------------------

export const CUBE_DAE = `<?xml version="1.0" encoding="utf-8"?>
<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
  <asset>
    <contributor><authoring_tool>fixture</authoring_tool></contributor>
    <created>2026-07-14T00:00:00</created>
    <modified>2026-07-14T00:00:00</modified>
    <unit name="meter" meter="1"/>
    <up_axis>Z_UP</up_axis>
  </asset>
  <library_geometries>
    <geometry id="Cube-mesh" name="Cube">
      <mesh>
        <source id="Cube-mesh-positions">
          <float_array id="Cube-mesh-positions-array" count="24">${V.map((v) => v.join(" ")).join(" ")}</float_array>
          <technique_common>
            <accessor source="#Cube-mesh-positions-array" count="8" stride="3">
              <param name="X" type="float"/>
              <param name="Y" type="float"/>
              <param name="Z" type="float"/>
            </accessor>
          </technique_common>
        </source>
        <vertices id="Cube-mesh-vertices">
          <input semantic="POSITION" source="#Cube-mesh-positions"/>
        </vertices>
        <triangles count="12">
          <input semantic="VERTEX" source="#Cube-mesh-vertices" offset="0"/>
          <p>${T.map((t) => t.join(" ")).join(" ")}</p>
        </triangles>
      </mesh>
    </geometry>
  </library_geometries>
  <library_visual_scenes>
    <visual_scene id="Scene" name="Scene">
      <node id="Cube" name="Cube" type="NODE">
        <matrix sid="transform">1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1</matrix>
        <instance_geometry url="#Cube-mesh"/>
      </node>
    </visual_scene>
  </library_visual_scenes>
  <scene>
    <instance_visual_scene url="#Scene"/>
  </scene>
</COLLADA>
`;

// ---- FBX (ASCII 7.4) -----------------------------------------------------

/**
 * ASCII FBX with the node subset three's FBXLoader requires: header with
 * FBXVersion >= 7000, a Geometry (Vertices + PolygonVertexIndex, where the
 * final index of each polygon is encoded as -(index + 1)), a Model of type
 * Mesh, and OO connections geometry -> model -> root(0).
 */
export const CUBE_FBX_ASCII = `; FBX 7.4.0 project file
FBXHeaderExtension:  {
	FBXHeaderVersion: 1003
	FBXVersion: 7400
	Creator: "fixture"
}
GlobalSettings:  {
	Version: 1000
	Properties70:  {
		P: "UpAxis", "int", "Integer", "",1
		P: "UpAxisSign", "int", "Integer", "",1
		P: "FrontAxis", "int", "Integer", "",2
		P: "FrontAxisSign", "int", "Integer", "",1
		P: "CoordAxis", "int", "Integer", "",0
		P: "CoordAxisSign", "int", "Integer", "",1
		P: "UnitScaleFactor", "double", "Number", "",1
	}
}
Objects:  {
	Geometry: 1000, "Geometry::Cube", "Mesh" {
		Vertices: *24 {
			a: ${V.map((v) => v.join(",")).join(",")}
		}
		PolygonVertexIndex: *36 {
			a: ${T.map((t) => `${t[0]},${t[1]},${-(t[2] + 1)}`).join(",")}
		}
		GeometryVersion: 124
	}
	Model: 2000, "Model::Cube", "Mesh" {
		Version: 232
		Properties70:  {
		}
		Shading: T
		Culling: "CullingOff"
	}
}
Connections:  {
	C: "OO",1000,2000
	C: "OO",2000,0
}
`;

// ---- OBJ / STL / GLB sources (same cube, hand-built per spec) -------------

export const CUBE_OBJ = `# cube fixture
${V.map((v) => `v ${v.join(" ")}`).join("\n")}
${T.map((t) => `f ${t[0] + 1} ${t[1] + 1} ${t[2] + 1}`).join("\n")}
`;

/** Binary STL of the cube (80-byte header, u32 count, 50 bytes per tri). */
export function makeCubeStlBinary(): Uint8Array {
  const out = new Uint8Array(84 + 12 * 50);
  const view = new DataView(out.buffer);
  view.setUint32(80, 12, true);
  let off = 84;
  for (const t of T) {
    off += 12; // zero normal; readers recompute
    for (const vi of t) {
      view.setFloat32(off, V[vi][0], true);
      view.setFloat32(off + 4, V[vi][1], true);
      view.setFloat32(off + 8, V[vi][2], true);
      off += 12;
    }
    off += 2; // attribute byte count
  }
  return out;
}

/**
 * GLB of the cube, hand-built per the container spec. When `interleaved` is
 * set, positions share a bufferView with a dummy vec3 (byteStride 24), which
 * exercises the strided accessor path that naive readers corrupt.
 */
export function makeCubeGlb(interleaved = false): Uint8Array {
  const enc = new TextEncoder();
  let json: object;
  let bin: Uint8Array;

  if (!interleaved) {
    const posBytes = 8 * 12;
    const idxBytes = 36 * 2;
    bin = new Uint8Array(posBytes + idxBytes);
    const pv = new Float32Array(bin.buffer, 0, 24);
    V.forEach((v, i) => pv.set(v, i * 3));
    const iv = new Uint16Array(bin.buffer, posBytes, 36);
    T.forEach((t, i) => iv.set(t, i * 3));
    json = {
      asset: { version: "2.0" },
      scene: 0,
      scenes: [{ nodes: [0] }],
      nodes: [{ mesh: 0 }],
      meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1, mode: 4 }] }],
      accessors: [
        { bufferView: 0, componentType: 5126, count: 8, type: "VEC3", min: [-1, -1, -1], max: [1, 1, 1] },
        { bufferView: 1, componentType: 5123, count: 36, type: "SCALAR" },
      ],
      bufferViews: [
        { buffer: 0, byteOffset: 0, byteLength: posBytes },
        { buffer: 0, byteOffset: posBytes, byteLength: idxBytes },
      ],
      buffers: [{ byteLength: bin.length }],
    };
  } else {
    // Interleave position + a dummy normal per vertex: stride 24 bytes.
    const stride = 24;
    const vtxBytes = 8 * stride;
    const idxBytes = 36 * 2;
    bin = new Uint8Array(vtxBytes + idxBytes);
    const view = new DataView(bin.buffer);
    V.forEach((v, i) => {
      view.setFloat32(i * stride, v[0], true);
      view.setFloat32(i * stride + 4, v[1], true);
      view.setFloat32(i * stride + 8, v[2], true);
      view.setFloat32(i * stride + 12, 9, true); // junk a naive reader would ingest
      view.setFloat32(i * stride + 16, 9, true);
      view.setFloat32(i * stride + 20, 9, true);
    });
    const iv = new Uint16Array(bin.buffer, vtxBytes, 36);
    T.forEach((t, i) => iv.set(t, i * 3));
    json = {
      asset: { version: "2.0" },
      scene: 0,
      scenes: [{ nodes: [0] }],
      nodes: [{ mesh: 0 }],
      meshes: [
        { primitives: [{ attributes: { POSITION: 0, NORMAL: 1 }, indices: 2, mode: 4 }] },
      ],
      accessors: [
        { bufferView: 0, byteOffset: 0, componentType: 5126, count: 8, type: "VEC3", min: [-1, -1, -1], max: [1, 1, 1] },
        { bufferView: 0, byteOffset: 12, componentType: 5126, count: 8, type: "VEC3" },
        { bufferView: 1, componentType: 5123, count: 36, type: "SCALAR" },
      ],
      bufferViews: [
        { buffer: 0, byteOffset: 0, byteLength: vtxBytes, byteStride: stride },
        { buffer: 0, byteOffset: vtxBytes, byteLength: idxBytes },
      ],
      buffers: [{ byteLength: bin.length }],
    };
  }

  const jsonBytes = enc.encode(JSON.stringify(json));
  const jsonPadded = (jsonBytes.length + 3) & ~3;
  const binPadded = (bin.length + 3) & ~3;
  const total = 12 + 8 + jsonPadded + 8 + binPadded;
  const out = new Uint8Array(total);
  const view = new DataView(out.buffer);
  view.setUint32(0, 0x46546c67, true);
  view.setUint32(4, 2, true);
  view.setUint32(8, total, true);
  view.setUint32(12, jsonPadded, true);
  view.setUint32(16, 0x4e4f534a, true);
  out.set(jsonBytes, 20);
  for (let i = jsonBytes.length; i < jsonPadded; i++) out[20 + i] = 0x20;
  const binHeader = 20 + jsonPadded;
  view.setUint32(binHeader, binPadded, true);
  view.setUint32(binHeader + 4, 0x004e4942, true);
  out.set(bin, binHeader + 8);
  return out;
}

/** .gltf whose single node scales the cube by 0.5 (expected volume: 1). */
export function makeScaledCubeGltfJson(): string {
  const doc = JSON.parse(makeCubeGltfJson()) as { nodes: Array<Record<string, unknown>> };
  doc.nodes[0] = { mesh: 0, scale: [0.5, 0.5, 0.5], translation: [10, 0, 0] };
  return JSON.stringify(doc);
}

// ---- 3DS (Autodesk 3D Studio, binary chunks) -----------------------------

/**
 * Minimal binary 3DS built chunk by chunk per the classic spec:
 * 0x4D4D main > 0x3D3D editor > 0x4000 named object > 0x4100 tri-mesh
 * > 0x4110 point array + 0x4120 face array.
 */
export function makeCube3ds(): Uint8Array {
  const enc = (id: number, payload: Uint8Array): Uint8Array => {
    const out = new Uint8Array(6 + payload.length);
    const view = new DataView(out.buffer);
    view.setUint16(0, id, true);
    view.setUint32(2, out.length, true);
    out.set(payload, 6);
    return out;
  };
  const concat = (...parts: Uint8Array[]): Uint8Array => {
    const total = parts.reduce((n, p) => n + p.length, 0);
    const out = new Uint8Array(total);
    let off = 0;
    for (const p of parts) {
      out.set(p, off);
      off += p.length;
    }
    return out;
  };

  // 0x4110 POINT_ARRAY: uint16 count + count * 3 float32
  const points = new Uint8Array(2 + 8 * 12);
  {
    const view = new DataView(points.buffer);
    view.setUint16(0, 8, true);
    V.forEach((v, i) => {
      view.setFloat32(2 + i * 12, v[0], true);
      view.setFloat32(2 + i * 12 + 4, v[1], true);
      view.setFloat32(2 + i * 12 + 8, v[2], true);
    });
  }
  // 0x4120 FACE_ARRAY: uint16 count + count * (3 x uint16 index + uint16 flags)
  const faces = new Uint8Array(2 + 12 * 8);
  {
    const view = new DataView(faces.buffer);
    view.setUint16(0, 12, true);
    T.forEach((t, i) => {
      view.setUint16(2 + i * 8, t[0], true);
      view.setUint16(2 + i * 8 + 2, t[1], true);
      view.setUint16(2 + i * 8 + 4, t[2], true);
      view.setUint16(2 + i * 8 + 6, 7, true); // ABC edge-visibility flags
    });
  }

  const triMesh = enc(0x4100, concat(enc(0x4110, points), enc(0x4120, faces)));
  const objName = new TextEncoder().encode("cube\0");
  const namedObject = enc(0x4000, concat(objName, triMesh));
  const meshVersion = new Uint8Array(4);
  new DataView(meshVersion.buffer).setUint32(0, 3, true);
  const editor = enc(0x3d3d, concat(enc(0x3d3e, meshVersion), namedObject));
  const m3dVersion = new Uint8Array(4);
  new DataView(m3dVersion.buffer).setUint32(0, 3, true);
  return enc(0x4d4d, concat(enc(0x0002, m3dVersion), editor));
}
